### ISSUE TITLE
Publish kotlin-jsr-223 on Maven Central and JCenter

### ISSUE THREAD

**Issue by renatoathaydes** [xafero/dynkt#1]
Hi.

Do you intend to publish this on Maven Central and JCenter?

It would be pretty awesome to do that. The kotlin-compiler jars are already available...

Also, would you be interested in adding OSGi support? I wanted to do that, but seeing how much effort it was to just add support for JSR-223 with a flat classpath, I would probably base that work on your project, so if you are interested I can try to make it work and submit a pull request.

**Comment by xafero** [comment]
Hi,

I do not know exactly how to upload to Maven's central repository, but I would like to do that.
I personally use JitPack: https://jitpack.io/#xafero/dynkt/81469ba243

Also I would like to update Kotlin to the new stable 1.x release (see #2). And OSGi support would be great, too (see #3).

Help would be very appreciated

**Comment by almibe** [comment]
I have a bunch of stuff I've been wanting to get in Maven Central but I've just never spent the time to learn how to do it.  Anyway, I'm planning on using my day off on Monday to finally read up on how to do it.  I can let you know if I figure it out.

**Comment by renatoathaydes** [comment]
Here's how I did it, using Bintray to do the hard bit for me (you still have to create an account with sonatype): https://twitter.com/renatoathaydes/status/692541460118380544

Let Bintray sign the jars and send them to Maven Central for you... it's the easiest and best way.

While I used Gradle, you can still easily do the same thing with Maven: http://veithen.github.io/2013/05/26/github-bintray-maven-release-plugin.html

**Comment by almibe** [comment]
I'm still working through them but there are some instructions on using bintray to publish to maven central here
https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/

**Comment by xafero** [comment]
Thanks @almibe for providing the link. It looks promising and I submitted the package to JCenter. Now it says that my request has been sent and Maven can't be synced with yet :-(

Anyways, I created it under 
https://bintray.com/xafero-solutions/xafero-source/DynKT

**Comment by renatoathaydes** [comment]
Your upload did not make it into jcenter.

See https://jcenter.bintray.com/com/xafero/.

The files are in Bintray, it's probably a matter of pressing a button there somewhere!

**Comment by xafero** [comment]
https://mvnrepository.com/artifact/com.xafero.dynkt/dynkt-jsr223/1.0.2
