### ISSUE TITLE
Update Kotlin

### ISSUE THREAD

**Issue by xafero** [xafero/dynkt#2]
I would like to update the compiler used to be the latest version

org.jetbrains.kotlin:kotlin-compiler:1.0.2
or
org.jetbrains.kotlin:kotlin-compiler-embeddable:1.0.2

**Comment by renatoathaydes** [comment]
I tried to do this but the kotlin compiler internal code is extremely unapproachable.

The current code is using a quite different API compared to the current version of the kotlin-compiler.

Hope you have better luck.

**Comment by xafero** [comment]
Newest embeddable compiler works

**Comment by renatoathaydes** [comment]
Great!
